CUBO = {
   ' int':{
        'int':{
            '+': 'int',
            '-': 'int',
            '/': 'int',
            '*': 'int',
            '<': 'bool',
            '>': 'bool',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'bool',
            '>=': 'bool'
        },
        'float':{
            '+': 'float',
            '-': 'float',
            '/': 'float',
            '*': 'float',
            '<': 'bool',
            '>': 'bool',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'bool',
            '>=': 'bool'

        },
        'bool':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err'

        },
        'char':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err'

        }
    },
    'float':{
        'int':{
            '+': 'float',
            '-': 'float',
            '/': 'float',
            '*': 'float',
            '<': 'bool',
            '>': 'bool',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'bool',
            '>=': 'bool'
        },
        'float':{
            '+': 'float',
            '-': 'float',
            '/': 'float',
            '*': 'float',
            '<': 'bool',
            '>': 'bool',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'bool',
            '>=': 'bool'
        },
        'bool':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err'
        },
        'char':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err'
        }
    },
    'bool':{
        'int':{
           '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err'
        },
        'float':{
           '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err'
        },
        'bool':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'bool',
            '>': 'bool',
            '&': 'bool',
            '|': 'bool',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err'
        },
        'char':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&': 'err',
            '|': 'err',
            '<>': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err'
        }
    },
    'char':{
        'int':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err'
        },
        'float':{
            '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err'
        },
        'bool':{
             '+': 'err',
            '-': 'err',
            '/': 'err',
            '*': 'err',
            '<': 'err',
            '>': 'err',
            '&': 'err',
            '|': 'err',
            '<>': 'bool',
            '==': 'bool',
            '<=': 'err',
            '>=': 'err'
        },
        'char':{
            '+': 'char',
            '-': 'char',
            '/': 'char',
            '*': 'char',
            '<': 'bool',
            '>': 'bool',
            '&': 'err',
            '|': 'err',
            '!=': 'bool',
            '==': 'bool',
            '<=': 'bool',
            '>=': 'bool'
        }
    },
}